server:
  port: 8010
spring:
  application:
    name: micro-service-consumer-movie
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true