server:
  port: 8761
eureka:
  client:
    register-with-eureka: false  #是否将自己注册到 Eureka Server , 默认为true. 由于当前应用就是server, 故而false
    fetch-registry: false
    service-url:
      default-zone: http://localhost:8761/eureka/